/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Pantallas.vistas.dialogos;

import Controlador.interfaz.ICoordinadorAplicacion;
import dtos.PerfilFiscalDTO;
import excepciones.CoordinadorException;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import utilerias.TextUtileria;
/**
 *
 * @author aaron
 */
public class DlgBuscarPerfil extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DlgBuscarPerfil.class.getName());
    private ICoordinadorAplicacion coordinador;
    /**
     * Creates new form DlgBuscarPerfil
     */
    public DlgBuscarPerfil(java.awt.Frame parent, boolean modal, ICoordinadorAplicacion coordinador) {
        super(parent, modal);
        this.coordinador = coordinador;
        initComponents();
        configuraciones();
    }

    private void configuraciones(){
        
        setTitle("Busqueda de PerfilFiscal");
        TextUtileria.estilizarText(txtEntrada, "Introduce rfc...");
        java.net.URL url = getClass().getResource("/img/hacienda.png");

        if(url != null){


            ImageIcon icon = new ImageIcon(url);

            int lblW = 143;
            int lblH = 33;

            Image img = icon.getImage().getScaledInstance(lblW, lblH, Image.SCALE_SMOOTH);

            lblHacienda.setIcon(new ImageIcon(img));
        }
    }
    
    private boolean validacionesEntrada(){
        if(txtEntrada.getText() == null || txtEntrada.getText().isBlank() || txtEntrada.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Campo vacío.");
            return false;
        }
        
        if(txtEntrada.getText().strip().length() != 12 && txtEntrada.getText().strip().length() != 13){
            JOptionPane.showMessageDialog(this, "El RFC debe ser entre 12-13 caracteres.");
            return false;
        }
        return true;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlContenedor = new javax.swing.JPanel();
        pnlSuperior = new javax.swing.JPanel();
        lblHacienda = new javax.swing.JLabel();
        txtTotal = new javax.swing.JLabel();
        txtRFC = new javax.swing.JLabel();
        txtEntrada = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        pnlContenedor.setBackground(new java.awt.Color(255, 255, 255));

        pnlSuperior.setBackground(new java.awt.Color(58, 91, 70));

        lblHacienda.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHacienda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/hacienda.png"))); // NOI18N
        lblHacienda.setText("imagen");

        javax.swing.GroupLayout pnlSuperiorLayout = new javax.swing.GroupLayout(pnlSuperior);
        pnlSuperior.setLayout(pnlSuperiorLayout);
        pnlSuperiorLayout.setHorizontalGroup(
            pnlSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 471, Short.MAX_VALUE)
            .addGroup(pnlSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlSuperiorLayout.createSequentialGroup()
                    .addGap(15, 15, 15)
                    .addComponent(lblHacienda, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(313, Short.MAX_VALUE)))
        );
        pnlSuperiorLayout.setVerticalGroup(
            pnlSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 45, Short.MAX_VALUE)
            .addGroup(pnlSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlSuperiorLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(lblHacienda, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        txtTotal.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtTotal.setForeground(new java.awt.Color(74, 21, 21));
        txtTotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtTotal.setText("Buscar perfil fiscal");

        txtRFC.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtRFC.setForeground(new java.awt.Color(51, 51, 51));
        txtRFC.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtRFC.setText("RFC:");

        txtEntrada.setBackground(java.awt.Color.white);
        txtEntrada.setForeground(new java.awt.Color(51, 51, 51));
        txtEntrada.setText("Introduce rfc...");
        txtEntrada.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        txtEntrada.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtEntrada.setMaximumSize(new java.awt.Dimension(100, 21));
        txtEntrada.setMinimumSize(new java.awt.Dimension(100, 21));
        txtEntrada.setOpaque(true);
        txtEntrada.setPreferredSize(new java.awt.Dimension(100, 21));
        txtEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEntradaActionPerformed(evt);
            }
        });

        btnBuscar.setBackground(new java.awt.Color(58, 91, 70));
        btnBuscar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar.setText("Buscar perfil");
        btnBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlContenedorLayout = new javax.swing.GroupLayout(pnlContenedor);
        pnlContenedor.setLayout(pnlContenedorLayout);
        pnlContenedorLayout.setHorizontalGroup(
            pnlContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContenedorLayout.createSequentialGroup()
                .addGroup(pnlContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlSuperior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlContenedorLayout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addGroup(pnlContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtRFC)
                            .addComponent(txtTotal)
                            .addGroup(pnlContenedorLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(pnlContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtEntrada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addContainerGap())
        );
        pnlContenedorLayout.setVerticalGroup(
            pnlContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContenedorLayout.createSequentialGroup()
                .addComponent(pnlSuperior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtTotal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtRFC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlContenedor, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlContenedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        if(validacionesEntrada()){
            try {
                if(coordinador.buscarPerfilFiscal(txtEntrada.getText(), null)!= null){
                   JOptionPane.showMessageDialog(this, "Perfil encontrado");
                   this.dispose();
                }
            } catch (CoordinadorException ex) {
                JOptionPane.showMessageDialog(this, "Suceso inesperado", "Fallo de operación", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void txtEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEntradaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEntradaActionPerformed
    public static void main(String args[]) {
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JLabel lblHacienda;
    private javax.swing.JPanel pnlContenedor;
    private javax.swing.JPanel pnlSuperior;
    private javax.swing.JTextField txtEntrada;
    private javax.swing.JLabel txtRFC;
    private javax.swing.JLabel txtTotal;
    // End of variables declaration//GEN-END:variables
}
