/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Pantallas.vistas.dialogos;

import Controlador.interfaz.ICoordinadorAplicacion;
import dtos.FacturaDTO;
import excepciones.CoordinadorException;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;

/**
 *
 * @author aaron
 */
public class DlgDetalleFactura extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DlgDetalleFactura.class.getName());
    private FacturaDTO factura;
    private ICoordinadorAplicacion coordinador;
    /**
     * Creates new form DlgDetalleFactura
     */
    public DlgDetalleFactura(java.awt.Frame parent, boolean modal, ICoordinadorAplicacion coordinador, FacturaDTO factura) {
        super(parent, modal);
        this.coordinador = coordinador;
        this.factura = factura;
        initComponents();
        configurarDatos();
    }

    private void configurarDatos() {
        if (factura == null) {
            return;
        }
        
        // --- Setear campos del perfil fiscal ---
        if (factura.getPerfil() != null) {
            campoRfc.setText(factura.getPerfil().getRfc());
            campoRazon.setText(factura.getPerfil().getNombre());
            campoCorreo.setText(factura.getPerfil().getCorreo());
            campoCP.setText(factura.getPerfil().getCodigoPostal());
            campoRegimen.setText(factura.getPerfil().getRegimenFiscal().getCodigo() + " - " + factura.getPerfil().getRegimenFiscal().getDescripcion());
        }
        
        // --- Setear campos de la factura ---
        campoTotal.setText(String.format("$%.2f", factura.getTotal()));
        campoMoneda.setText(factura.getMoneda() != null ? factura.getMoneda() : "MXN");
        
        // --- Setear método de pago ---
        if (factura.getMetodoPago() != null) {
            campoMetodoPago.setText(factura.getMetodoPago());
        }
        
        // --- Setear fecha de compra ---
        if (factura.getFechaCompra() != null) {
            campoFechaCOmpra.setText(factura.getFechaCompra().format(DateTimeFormatter.ISO_DATE));
        }
        
        // --- Setear uso CFDI ---
        if (factura.getUsoCfdi() != null) {
            campoUso.setText(factura.getUsoCfdi().getCodigo() + " - " + factura.getUsoCfdi().getDescripcion());
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblDatosFiscales = new javax.swing.JLabel();
        txtRFC = new javax.swing.JLabel();
        txtRazonSocial = new javax.swing.JLabel();
        campoTotal = new javax.swing.JTextField();
        campoFechaCOmpra = new javax.swing.JTextField();
        campoRfc = new javax.swing.JTextField();
        campoMetodoPago = new javax.swing.JTextField();
        campoRazon = new javax.swing.JTextField();
        campoMoneda = new javax.swing.JTextField();
        txtCP = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JLabel();
        campoCorreo = new javax.swing.JTextField();
        txtRegimenFiscal = new javax.swing.JLabel();
        campoCP = new javax.swing.JTextField();
        txtUsoCFDI = new javax.swing.JLabel();
        txtTotal = new javax.swing.JLabel();
        txtMétodoPago = new javax.swing.JLabel();
        txtFechaReserva = new javax.swing.JLabel();
        txtMoneda = new javax.swing.JLabel();
        campoRegimen = new javax.swing.JTextField();
        campoUso = new javax.swing.JTextField();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(54, 76, 62));

        lblDatosFiscales.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblDatosFiscales.setForeground(new java.awt.Color(255, 255, 255));
        lblDatosFiscales.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDatosFiscales.setText("Detalle Factura");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(lblDatosFiscales, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDatosFiscales, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txtRFC.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        txtRFC.setForeground(new java.awt.Color(51, 51, 51));
        txtRFC.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtRFC.setText("RFC:");

        txtRazonSocial.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        txtRazonSocial.setForeground(new java.awt.Color(51, 51, 51));
        txtRazonSocial.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtRazonSocial.setText("Razón social:");

        campoTotal.setEditable(false);
        campoTotal.setBackground(new java.awt.Color(255, 255, 255));
        campoTotal.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        campoTotal.setForeground(new java.awt.Color(0, 0, 0));
        campoTotal.setText("jTextField1");
        campoTotal.setBorder(null);
        campoTotal.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        campoTotal.setMaximumSize(new java.awt.Dimension(100, 21));
        campoTotal.setMinimumSize(new java.awt.Dimension(100, 21));
        campoTotal.setPreferredSize(new java.awt.Dimension(100, 21));

        campoFechaCOmpra.setEditable(false);
        campoFechaCOmpra.setBackground(new java.awt.Color(255, 255, 255));
        campoFechaCOmpra.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        campoFechaCOmpra.setForeground(new java.awt.Color(0, 0, 0));
        campoFechaCOmpra.setText("jTextField1");
        campoFechaCOmpra.setBorder(null);
        campoFechaCOmpra.setMaximumSize(new java.awt.Dimension(100, 21));
        campoFechaCOmpra.setMinimumSize(new java.awt.Dimension(100, 21));
        campoFechaCOmpra.setPreferredSize(new java.awt.Dimension(100, 21));

        campoRfc.setEditable(false);
        campoRfc.setBackground(new java.awt.Color(255, 255, 255));
        campoRfc.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        campoRfc.setForeground(new java.awt.Color(0, 0, 0));
        campoRfc.setText("jTextField1");
        campoRfc.setBorder(null);
        campoRfc.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        campoRfc.setMaximumSize(new java.awt.Dimension(100, 21));
        campoRfc.setMinimumSize(new java.awt.Dimension(100, 21));
        campoRfc.setPreferredSize(new java.awt.Dimension(100, 21));

        campoMetodoPago.setEditable(false);
        campoMetodoPago.setBackground(new java.awt.Color(255, 255, 255));
        campoMetodoPago.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        campoMetodoPago.setForeground(new java.awt.Color(0, 0, 0));
        campoMetodoPago.setText("jTextField1");
        campoMetodoPago.setBorder(null);
        campoMetodoPago.setMaximumSize(new java.awt.Dimension(100, 21));
        campoMetodoPago.setMinimumSize(new java.awt.Dimension(100, 21));
        campoMetodoPago.setPreferredSize(new java.awt.Dimension(100, 21));

        campoRazon.setEditable(false);
        campoRazon.setBackground(new java.awt.Color(255, 255, 255));
        campoRazon.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        campoRazon.setForeground(new java.awt.Color(0, 0, 0));
        campoRazon.setText("jTextField1");
        campoRazon.setBorder(null);
        campoRazon.setMaximumSize(new java.awt.Dimension(100, 21));
        campoRazon.setMinimumSize(new java.awt.Dimension(100, 21));
        campoRazon.setPreferredSize(new java.awt.Dimension(100, 21));

        campoMoneda.setEditable(false);
        campoMoneda.setBackground(new java.awt.Color(255, 255, 255));
        campoMoneda.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        campoMoneda.setForeground(new java.awt.Color(0, 0, 0));
        campoMoneda.setText("jTextField1");
        campoMoneda.setBorder(null);
        campoMoneda.setMaximumSize(new java.awt.Dimension(100, 21));
        campoMoneda.setMinimumSize(new java.awt.Dimension(100, 21));
        campoMoneda.setPreferredSize(new java.awt.Dimension(100, 21));

        txtCP.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        txtCP.setForeground(new java.awt.Color(51, 51, 51));
        txtCP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtCP.setText("Código Postal:");

        txtCorreo.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        txtCorreo.setForeground(new java.awt.Color(51, 51, 51));
        txtCorreo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtCorreo.setText("Correo:");

        campoCorreo.setEditable(false);
        campoCorreo.setBackground(new java.awt.Color(255, 255, 255));
        campoCorreo.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        campoCorreo.setForeground(new java.awt.Color(0, 0, 0));
        campoCorreo.setText("jTextField1");
        campoCorreo.setBorder(null);
        campoCorreo.setMaximumSize(new java.awt.Dimension(100, 21));
        campoCorreo.setMinimumSize(new java.awt.Dimension(100, 21));
        campoCorreo.setPreferredSize(new java.awt.Dimension(100, 21));

        txtRegimenFiscal.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        txtRegimenFiscal.setForeground(new java.awt.Color(51, 51, 51));
        txtRegimenFiscal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtRegimenFiscal.setText("Régimen fiscal:");

        campoCP.setEditable(false);
        campoCP.setBackground(new java.awt.Color(255, 255, 255));
        campoCP.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        campoCP.setForeground(new java.awt.Color(0, 0, 0));
        campoCP.setText("jTextField1");
        campoCP.setBorder(null);
        campoCP.setMaximumSize(new java.awt.Dimension(100, 21));
        campoCP.setMinimumSize(new java.awt.Dimension(100, 21));
        campoCP.setPreferredSize(new java.awt.Dimension(100, 21));

        txtUsoCFDI.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        txtUsoCFDI.setForeground(new java.awt.Color(51, 51, 51));
        txtUsoCFDI.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtUsoCFDI.setText("UsoCFDI:");

        txtTotal.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        txtTotal.setForeground(new java.awt.Color(51, 51, 51));
        txtTotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtTotal.setText("Total pagado:");

        txtMétodoPago.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        txtMétodoPago.setForeground(new java.awt.Color(51, 51, 51));
        txtMétodoPago.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtMétodoPago.setText("Método de pago:");

        txtFechaReserva.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        txtFechaReserva.setForeground(new java.awt.Color(51, 51, 51));
        txtFechaReserva.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtFechaReserva.setText("Fecha de compra");

        txtMoneda.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        txtMoneda.setForeground(new java.awt.Color(51, 51, 51));
        txtMoneda.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtMoneda.setText("Moneda:");

        campoRegimen.setEditable(false);
        campoRegimen.setBackground(new java.awt.Color(255, 255, 255));
        campoRegimen.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        campoRegimen.setForeground(new java.awt.Color(0, 0, 0));
        campoRegimen.setText("jTextField1");
        campoRegimen.setBorder(null);
        campoRegimen.setMaximumSize(new java.awt.Dimension(100, 21));
        campoRegimen.setMinimumSize(new java.awt.Dimension(100, 21));
        campoRegimen.setPreferredSize(new java.awt.Dimension(100, 21));

        campoUso.setEditable(false);
        campoUso.setBackground(new java.awt.Color(255, 255, 255));
        campoUso.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        campoUso.setForeground(new java.awt.Color(0, 0, 0));
        campoUso.setText("jTextField1");
        campoUso.setBorder(null);
        campoUso.setMaximumSize(new java.awt.Dimension(100, 21));
        campoUso.setMinimumSize(new java.awt.Dimension(100, 21));
        campoUso.setPreferredSize(new java.awt.Dimension(100, 21));

        btnAceptar.setBackground(new java.awt.Color(54, 76, 62));
        btnAceptar.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        btnAceptar.setForeground(new java.awt.Color(255, 255, 255));
        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        btnCancelar.setBackground(new java.awt.Color(54, 76, 62));
        btnCancelar.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campoCP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(campoCorreo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(campoRazon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(campoUso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCP)
                                    .addComponent(txtRFC)
                                    .addComponent(txtCorreo)
                                    .addComponent(txtUsoCFDI)
                                    .addComponent(campoRfc, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtRazonSocial))
                                .addGap(0, 52, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(campoRegimen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(campoFechaCOmpra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(campoMetodoPago, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(campoMoneda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtTotal)
                            .addComponent(txtMoneda)
                            .addComponent(txtMétodoPago)
                            .addComponent(txtFechaReserva)
                            .addComponent(txtRegimenFiscal)
                            .addComponent(campoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnCancelar)
                        .addGap(29, 29, 29)
                        .addComponent(btnAceptar)
                        .addGap(172, 172, 172))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRFC)
                    .addComponent(txtTotal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoRfc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMoneda)
                    .addComponent(txtRazonSocial))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(campoRazon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoMoneda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtMétodoPago)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoMetodoPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtFechaReserva)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoFechaCOmpra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtRegimenFiscal))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtCorreo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtCP)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoCP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtUsoCFDI)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(campoRegimen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoUso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnAceptar))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        coordinador.mostrarDatosFactura(factura);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        try {
            if(coordinador.timbrarFactura(factura)){
                JOptionPane.showMessageDialog(this, "Su factura ha sido enviada a : " + factura.getPerfil().getCorreo());
                this.dispose();
            }
        } catch (CoordinadorException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
            this.dispose();
        }
        
    }//GEN-LAST:event_btnAceptarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JTextField campoCP;
    private javax.swing.JTextField campoCorreo;
    private javax.swing.JTextField campoFechaCOmpra;
    private javax.swing.JTextField campoMetodoPago;
    private javax.swing.JTextField campoMoneda;
    private javax.swing.JTextField campoRazon;
    private javax.swing.JTextField campoRegimen;
    private javax.swing.JTextField campoRfc;
    private javax.swing.JTextField campoTotal;
    private javax.swing.JTextField campoUso;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblDatosFiscales;
    private javax.swing.JLabel txtCP;
    private javax.swing.JLabel txtCorreo;
    private javax.swing.JLabel txtFechaReserva;
    private javax.swing.JLabel txtMoneda;
    private javax.swing.JLabel txtMétodoPago;
    private javax.swing.JLabel txtRFC;
    private javax.swing.JLabel txtRazonSocial;
    private javax.swing.JLabel txtRegimenFiscal;
    private javax.swing.JLabel txtTotal;
    private javax.swing.JLabel txtUsoCFDI;
    // End of variables declaration//GEN-END:variables
}
