/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Pantallas;

import Controlador.interfaz.ICoordinadorAplicacion;
import dtos.ENUMS.UsoCfdiDTO;
import dtos.FacturaDTO;
import dtos.PerfilFiscalDTO;
import dtos.ReservacionDTO;
import java.awt.Image;
import java.time.format.DateTimeFormatter;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
/**
 *
 * @author aaron
 */
public class FrmDatosFacturar extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmDatosFacturar.class.getName());
    private ICoordinadorAplicacion coordinador;
    private FacturaDTO factura;
    
    /**
     * Creates new form FrmDatosFacturar
     */
    public FrmDatosFacturar(ICoordinadorAplicacion coordinador, FacturaDTO factura) {
        this.coordinador = coordinador;
        this.factura = factura;
        initComponents();
        configuraciones();
    }
    
    private void configuraciones(){
        
        java.net.URL url = getClass().getResource("/img/hacienda.png");
        
        if(url != null){
            
            
            ImageIcon icon = new ImageIcon(url);
            
            int lblW = 150;
            int lblH = 80;
            
            Image img = icon.getImage().getScaledInstance(lblW, lblH, Image.SCALE_SMOOTH);
            
            lblHacienda.setIcon(new ImageIcon(img));
        }
        
        // setear los acampos de perfil fiscal
        campoRfc.setText(factura.getPerfil().getRfc());
        campoRazon.setText(factura.getPerfil().getNombre());
        campoCorreo.setText(factura.getPerfil().getCorreo());
        campoCP.setText(factura.getPerfil().getCodigoPostal());
        campoRegimen.setText(factura.getPerfil().getRegimenFiscal().getCodigo() +" "+ factura.getPerfil().getRegimenFiscal().getDescripcion());
        
        // setteo de campos de boleto
        campoTotal.setText(String.valueOf(factura.getTotal()));
        campoMoneda.setText("MXN");
        campoMetodo.setText(factura.getMetodoPago());
        campoFecha.setText(factura.getFechaCompra().format(DateTimeFormatter.ISO_DATE));
        
    }
    
    private boolean recogerDatos(){
        // Validar correo
        if(campoCorreo.getText().isBlank() || campoCorreo.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "El correo no puede estar vacío.");
            return false;
        }
        if(!validarCorreo()){
            JOptionPane.showMessageDialog(this, "Formato incorrecto de correo.");
            return false;
        }

        // Validar código postal
        if(!esCodigoPostalValido(campoCP.getText())){
            JOptionPane.showMessageDialog(this, "El código postal debe tener exactamente 5 números.");
            return false;
        }

        // Si todo está bien, asignar valores
        this.factura.getPerfil().setCorreo(campoCorreo.getText().strip());
        this.factura.getPerfil().setCodigoPostal(campoCP.getText().strip());
        this.factura.setUsoCfdi((UsoCfdiDTO) cbxUsocfdi.getSelectedItem());
        return true;
    }

    public boolean esCodigoPostalValido(String str) {
        if (str == null || str.isBlank()) {
            return false;  
        }
        return str.matches("^\\d{5}$");
    }

    private boolean validarCorreo(){
        if(campoCorreo.getText().isBlank() || campoCorreo.getText().isEmpty()){
            return false;  
        }

        String regex = "^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$";
        Pattern pattern = Pattern.compile(regex);
        Matcher matcher = pattern.matcher(campoCorreo.getText());

        return matcher.matches();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlContenedor = new javax.swing.JPanel();
        pnlGris = new javax.swing.JPanel();
        lblDatosFiscales = new javax.swing.JLabel();
        txtRFC = new javax.swing.JLabel();
        txtRazonSocial = new javax.swing.JLabel();
        txtCP = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JLabel();
        txtRegimenFiscal = new javax.swing.JLabel();
        txtUsoCFDI = new javax.swing.JLabel();
        txtTotal = new javax.swing.JLabel();
        txtMétodoPago = new javax.swing.JLabel();
        txtFechaReserva = new javax.swing.JLabel();
        txtMoneda = new javax.swing.JLabel();
        campoRfc = new javax.swing.JTextField();
        campoRazon = new javax.swing.JTextField();
        campoCorreo = new javax.swing.JTextField();
        campoCP = new javax.swing.JTextField();
        cbxUsocfdi = new javax.swing.JComboBox<>();
        campoTotal = new javax.swing.JTextField();
        campoFecha = new javax.swing.JTextField();
        campoMetodo = new javax.swing.JTextField();
        campoMoneda = new javax.swing.JTextField();
        btnGenerar = new javax.swing.JButton();
        campoRegimen = new javax.swing.JTextField();
        pnlSuperior = new javax.swing.JPanel();
        lblHacienda = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(216, 216, 216));
        setResizable(false);

        pnlContenedor.setBackground(new java.awt.Color(255, 255, 255));

        pnlGris.setBackground(new java.awt.Color(216, 216, 216));
        pnlGris.setForeground(new java.awt.Color(216, 216, 216));

        javax.swing.GroupLayout pnlGrisLayout = new javax.swing.GroupLayout(pnlGris);
        pnlGris.setLayout(pnlGrisLayout);
        pnlGrisLayout.setHorizontalGroup(
            pnlGrisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );
        pnlGrisLayout.setVerticalGroup(
            pnlGrisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        lblDatosFiscales.setFont(new java.awt.Font("Roboto", 1, 26)); // NOI18N
        lblDatosFiscales.setForeground(new java.awt.Color(0, 0, 0));
        lblDatosFiscales.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDatosFiscales.setText("Datos Fiscales");

        txtRFC.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        txtRFC.setForeground(new java.awt.Color(51, 51, 51));
        txtRFC.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtRFC.setText("RFC:");

        txtRazonSocial.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        txtRazonSocial.setForeground(new java.awt.Color(51, 51, 51));
        txtRazonSocial.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtRazonSocial.setText("Razón social:");

        txtCP.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        txtCP.setForeground(new java.awt.Color(51, 51, 51));
        txtCP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtCP.setText("Código Postal:");

        txtCorreo.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        txtCorreo.setForeground(new java.awt.Color(51, 51, 51));
        txtCorreo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtCorreo.setText("Correo:");

        txtRegimenFiscal.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        txtRegimenFiscal.setForeground(new java.awt.Color(51, 51, 51));
        txtRegimenFiscal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtRegimenFiscal.setText("Régimen fiscal:");

        txtUsoCFDI.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        txtUsoCFDI.setForeground(new java.awt.Color(51, 51, 51));
        txtUsoCFDI.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtUsoCFDI.setText("UsoCFDI:");

        txtTotal.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        txtTotal.setForeground(new java.awt.Color(51, 51, 51));
        txtTotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtTotal.setText("Total pagado:");

        txtMétodoPago.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        txtMétodoPago.setForeground(new java.awt.Color(51, 51, 51));
        txtMétodoPago.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtMétodoPago.setText("Método de pago:");

        txtFechaReserva.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        txtFechaReserva.setForeground(new java.awt.Color(51, 51, 51));
        txtFechaReserva.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtFechaReserva.setText("Fecha de compra:");

        txtMoneda.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        txtMoneda.setForeground(new java.awt.Color(51, 51, 51));
        txtMoneda.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtMoneda.setText("Moneda:");

        campoRfc.setEditable(false);
        campoRfc.setBackground(java.awt.Color.white);
        campoRfc.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        campoRfc.setForeground(new java.awt.Color(51, 51, 51));
        campoRfc.setText("jTextField1");
        campoRfc.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        campoRfc.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        campoRfc.setMaximumSize(new java.awt.Dimension(100, 21));
        campoRfc.setMinimumSize(new java.awt.Dimension(100, 21));
        campoRfc.setOpaque(true);
        campoRfc.setPreferredSize(new java.awt.Dimension(100, 21));

        campoRazon.setEditable(false);
        campoRazon.setBackground(java.awt.Color.white);
        campoRazon.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        campoRazon.setForeground(new java.awt.Color(51, 51, 51));
        campoRazon.setText("jTextField1");
        campoRazon.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        campoRazon.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        campoRazon.setMaximumSize(new java.awt.Dimension(100, 21));
        campoRazon.setMinimumSize(new java.awt.Dimension(100, 21));
        campoRazon.setOpaque(true);
        campoRazon.setPreferredSize(new java.awt.Dimension(100, 21));

        campoCorreo.setBackground(java.awt.Color.white);
        campoCorreo.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        campoCorreo.setText("jTextField1");
        campoCorreo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        campoCorreo.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        campoCorreo.setMaximumSize(new java.awt.Dimension(100, 21));
        campoCorreo.setMinimumSize(new java.awt.Dimension(100, 21));
        campoCorreo.setOpaque(true);
        campoCorreo.setPreferredSize(new java.awt.Dimension(100, 21));

        campoCP.setBackground(java.awt.Color.white);
        campoCP.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        campoCP.setText("jTextField1");
        campoCP.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        campoCP.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        campoCP.setMaximumSize(new java.awt.Dimension(100, 21));
        campoCP.setMinimumSize(new java.awt.Dimension(100, 21));
        campoCP.setOpaque(true);
        campoCP.setPreferredSize(new java.awt.Dimension(100, 21));

        cbxUsocfdi.setBackground(java.awt.Color.white);
        cbxUsocfdi.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        cbxUsocfdi.setModel(new javax.swing.DefaultComboBoxModel<>(UsoCfdiDTO.values()));
        cbxUsocfdi.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        cbxUsocfdi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cbxUsocfdi.setMaximumSize(new java.awt.Dimension(100, 21));
        cbxUsocfdi.setMinimumSize(new java.awt.Dimension(100, 21));
        cbxUsocfdi.setOpaque(true);
        cbxUsocfdi.setPreferredSize(new java.awt.Dimension(100, 21));
        cbxUsocfdi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxUsocfdiActionPerformed(evt);
            }
        });

        campoTotal.setEditable(false);
        campoTotal.setBackground(java.awt.Color.white);
        campoTotal.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        campoTotal.setForeground(new java.awt.Color(51, 51, 51));
        campoTotal.setText("jTextField1");
        campoTotal.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        campoTotal.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        campoTotal.setMaximumSize(new java.awt.Dimension(100, 21));
        campoTotal.setMinimumSize(new java.awt.Dimension(100, 21));
        campoTotal.setOpaque(true);
        campoTotal.setPreferredSize(new java.awt.Dimension(100, 21));

        campoFecha.setEditable(false);
        campoFecha.setBackground(java.awt.Color.white);
        campoFecha.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        campoFecha.setForeground(new java.awt.Color(51, 51, 51));
        campoFecha.setText("jTextField1");
        campoFecha.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        campoFecha.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        campoFecha.setMaximumSize(new java.awt.Dimension(100, 21));
        campoFecha.setMinimumSize(new java.awt.Dimension(100, 21));
        campoFecha.setOpaque(true);
        campoFecha.setPreferredSize(new java.awt.Dimension(100, 21));

        campoMetodo.setEditable(false);
        campoMetodo.setBackground(java.awt.Color.white);
        campoMetodo.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        campoMetodo.setForeground(new java.awt.Color(51, 51, 51));
        campoMetodo.setText("jTextField1");
        campoMetodo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        campoMetodo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        campoMetodo.setMaximumSize(new java.awt.Dimension(100, 21));
        campoMetodo.setMinimumSize(new java.awt.Dimension(100, 21));
        campoMetodo.setOpaque(true);
        campoMetodo.setPreferredSize(new java.awt.Dimension(100, 21));
        campoMetodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoMetodoActionPerformed(evt);
            }
        });

        campoMoneda.setEditable(false);
        campoMoneda.setBackground(java.awt.Color.white);
        campoMoneda.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        campoMoneda.setForeground(new java.awt.Color(51, 51, 51));
        campoMoneda.setText("jTextField1");
        campoMoneda.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        campoMoneda.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        campoMoneda.setMaximumSize(new java.awt.Dimension(100, 21));
        campoMoneda.setMinimumSize(new java.awt.Dimension(100, 21));
        campoMoneda.setOpaque(true);
        campoMoneda.setPreferredSize(new java.awt.Dimension(100, 21));

        btnGenerar.setBackground(new java.awt.Color(58, 91, 70));
        btnGenerar.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        btnGenerar.setForeground(new java.awt.Color(255, 255, 255));
        btnGenerar.setText("Generar Factura");
        btnGenerar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarActionPerformed(evt);
            }
        });

        campoRegimen.setEditable(false);
        campoRegimen.setBackground(java.awt.Color.white);
        campoRegimen.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        campoRegimen.setForeground(new java.awt.Color(51, 51, 51));
        campoRegimen.setText("jTextField1");
        campoRegimen.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        campoRegimen.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        campoRegimen.setMaximumSize(new java.awt.Dimension(100, 21));
        campoRegimen.setMinimumSize(new java.awt.Dimension(100, 21));
        campoRegimen.setOpaque(true);
        campoRegimen.setPreferredSize(new java.awt.Dimension(100, 21));

        javax.swing.GroupLayout pnlContenedorLayout = new javax.swing.GroupLayout(pnlContenedor);
        pnlContenedor.setLayout(pnlContenedorLayout);
        pnlContenedorLayout.setHorizontalGroup(
            pnlContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContenedorLayout.createSequentialGroup()
                .addComponent(pnlGris, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pnlContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlContenedorLayout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(pnlContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlContenedorLayout.createSequentialGroup()
                                .addComponent(txtRFC)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(pnlContenedorLayout.createSequentialGroup()
                                .addGroup(pnlContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(campoCorreo, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                                    .addComponent(campoRazon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbxUsocfdi, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(campoCP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(pnlContenedorLayout.createSequentialGroup()
                                        .addGroup(pnlContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtCP)
                                            .addComponent(txtCorreo)
                                            .addComponent(txtUsoCFDI)
                                            .addComponent(txtRazonSocial))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(campoRfc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(98, 98, 98)
                                .addGroup(pnlContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtTotal)
                                    .addComponent(txtMoneda)
                                    .addComponent(txtMétodoPago)
                                    .addComponent(txtFechaReserva)
                                    .addComponent(txtRegimenFiscal)
                                    .addComponent(campoMoneda, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                                    .addComponent(campoTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(campoMetodo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(campoFecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(campoRegimen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(94, 94, 94))))
                    .addGroup(pnlContenedorLayout.createSequentialGroup()
                        .addGroup(pnlContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlContenedorLayout.createSequentialGroup()
                                .addGap(174, 174, 174)
                                .addComponent(lblDatosFiscales, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlContenedorLayout.createSequentialGroup()
                                .addGap(190, 190, 190)
                                .addComponent(btnGenerar)))
                        .addContainerGap())))
        );
        pnlContenedorLayout.setVerticalGroup(
            pnlContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlGris, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlContenedorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDatosFiscales, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(pnlContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRFC)
                    .addComponent(txtTotal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoRfc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMoneda)
                    .addComponent(txtRazonSocial))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(campoRazon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoMoneda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(pnlContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlContenedorLayout.createSequentialGroup()
                        .addComponent(txtMétodoPago)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoMetodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtFechaReserva)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtRegimenFiscal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoRegimen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlContenedorLayout.createSequentialGroup()
                        .addComponent(txtCorreo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtCP)
                        .addGap(6, 6, 6)
                        .addComponent(campoCP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtUsoCFDI)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbxUsocfdi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(32, 32, 32)
                .addComponent(btnGenerar, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pnlSuperior.setBackground(new java.awt.Color(58, 91, 70));

        lblHacienda.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHacienda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/hacienda.png"))); // NOI18N
        lblHacienda.setText("imagen");

        javax.swing.GroupLayout pnlSuperiorLayout = new javax.swing.GroupLayout(pnlSuperior);
        pnlSuperior.setLayout(pnlSuperiorLayout);
        pnlSuperiorLayout.setHorizontalGroup(
            pnlSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSuperiorLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblHacienda, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnlSuperiorLayout.setVerticalGroup(
            pnlSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSuperiorLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblHacienda, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlSuperior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlContenedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(pnlSuperior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(pnlContenedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarActionPerformed
        if(recogerDatos()){
            this.coordinador.mostrarResumenDatosFactura(this.factura);
        }
    }//GEN-LAST:event_btnGenerarActionPerformed
    private void campoMetodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoMetodoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoMetodoActionPerformed

    private void cbxUsocfdiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxUsocfdiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxUsocfdiActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGenerar;
    private javax.swing.JTextField campoCP;
    private javax.swing.JTextField campoCorreo;
    private javax.swing.JTextField campoFecha;
    private javax.swing.JTextField campoMetodo;
    private javax.swing.JTextField campoMoneda;
    private javax.swing.JTextField campoRazon;
    private javax.swing.JTextField campoRegimen;
    private javax.swing.JTextField campoRfc;
    private javax.swing.JTextField campoTotal;
    private javax.swing.JComboBox<UsoCfdiDTO> cbxUsocfdi;
    private javax.swing.JLabel lblDatosFiscales;
    private javax.swing.JLabel lblHacienda;
    private javax.swing.JPanel pnlContenedor;
    private javax.swing.JPanel pnlGris;
    private javax.swing.JPanel pnlSuperior;
    private javax.swing.JLabel txtCP;
    private javax.swing.JLabel txtCorreo;
    private javax.swing.JLabel txtFechaReserva;
    private javax.swing.JLabel txtMoneda;
    private javax.swing.JLabel txtMétodoPago;
    private javax.swing.JLabel txtRFC;
    private javax.swing.JLabel txtRazonSocial;
    private javax.swing.JLabel txtRegimenFiscal;
    private javax.swing.JLabel txtTotal;
    private javax.swing.JLabel txtUsoCFDI;
    // End of variables declaration//GEN-END:variables
}
