/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Pantallas;

import Controlador.interfaz.ICoordinadorAplicacion;
import dtos.CobroDTO;
import dtos.PagoDTO;
import dtos.ReservacionDTO;
import dtos.TarjetaDTO;
import excepciones.CoordinadorException;
import javax.swing.JOptionPane;
import utilerias.BotonUtileria;

/**
 *
 * @author Aaron Burciaga - 262788
 * @author Brian Sandoval - 262741
 * @author Dayanara Peralta - 262695
 * @author María Valdez - 262775
 */
public class FrmPago extends javax.swing.JFrame {

    private ICoordinadorAplicacion coordinador;
    private ReservacionDTO reservacion;

    public FrmPago(ICoordinadorAplicacion coordinador, ReservacionDTO reservacion) {
        this.coordinador = coordinador;
        this.reservacion = reservacion;

        initComponents();

        BotonUtileria.estilizarBoton(btnPagar);
        BotonUtileria.estilizarBoton(btnVolver);
    }

    private void mostrarMensaje(String message) {
        JOptionPane.showMessageDialog(null, message, "Advertencia", JOptionPane.WARNING_MESSAGE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelInicio = new javax.swing.JPanel();
        jPanelAzul = new javax.swing.JPanel();
        textPotroEventos = new javax.swing.JLabel();
        jPanelAzulOscuro = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        panContenedor = new javax.swing.JPanel();
        txtNoTarjeta = new javax.swing.JTextField();
        textCorreo1 = new javax.swing.JLabel();
        textCorreo2 = new javax.swing.JLabel();
        txtFechaExpiracion = new javax.swing.JTextField();
        textCorreo3 = new javax.swing.JLabel();
        txtCVV = new javax.swing.JTextField();
        btnPagar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnVolver = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setResizable(false);

        jPanelInicio.setBackground(new java.awt.Color(255, 255, 255));

        jPanelAzul.setBackground(new java.awt.Color(31, 92, 204));
        jPanelAzul.setPreferredSize(new java.awt.Dimension(597, 50));

        textPotroEventos.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N
        textPotroEventos.setForeground(new java.awt.Color(255, 255, 255));
        textPotroEventos.setText("PotroEventos");

        jPanelAzulOscuro.setBackground(new java.awt.Color(0, 49, 141));

        javax.swing.GroupLayout jPanelAzulOscuroLayout = new javax.swing.GroupLayout(jPanelAzulOscuro);
        jPanelAzulOscuro.setLayout(jPanelAzulOscuroLayout);
        jPanelAzulOscuroLayout.setHorizontalGroup(
            jPanelAzulOscuroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanelAzulOscuroLayout.setVerticalGroup(
            jPanelAzulOscuroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanelAzulLayout = new javax.swing.GroupLayout(jPanelAzul);
        jPanelAzul.setLayout(jPanelAzulLayout);
        jPanelAzulLayout.setHorizontalGroup(
            jPanelAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAzulLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(textPotroEventos)
                .addContainerGap(293, Short.MAX_VALUE))
            .addComponent(jPanelAzulOscuro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelAzulLayout.setVerticalGroup(
            jPanelAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAzulLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textPotroEventos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelAzulOscuro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panContenedor.setBackground(new java.awt.Color(255, 255, 255));

        txtNoTarjeta.setBackground(new java.awt.Color(234, 230, 230));
        txtNoTarjeta.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        txtNoTarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNoTarjetaActionPerformed(evt);
            }
        });
        txtNoTarjeta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNoTarjetaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNoTarjetaKeyTyped(evt);
            }
        });

        textCorreo1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        textCorreo1.setText("No. tarjeta");

        textCorreo2.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        textCorreo2.setText("Fecha expiración");

        txtFechaExpiracion.setBackground(new java.awt.Color(234, 230, 230));
        txtFechaExpiracion.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        txtFechaExpiracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaExpiracionActionPerformed(evt);
            }
        });
        txtFechaExpiracion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFechaExpiracionKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFechaExpiracionKeyTyped(evt);
            }
        });

        textCorreo3.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        textCorreo3.setText("CVV");

        txtCVV.setBackground(new java.awt.Color(234, 230, 230));
        txtCVV.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        txtCVV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCVVActionPerformed(evt);
            }
        });
        txtCVV.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCVVKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCVVKeyTyped(evt);
            }
        });

        btnPagar.setBackground(new java.awt.Color(44, 114, 243));
        btnPagar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPagarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPagarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPagarMouseExited(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Pagar");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout btnPagarLayout = new javax.swing.GroupLayout(btnPagar);
        btnPagar.setLayout(btnPagarLayout);
        btnPagarLayout.setHorizontalGroup(
            btnPagarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
        );
        btnPagarLayout.setVerticalGroup(
            btnPagarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
        );

        btnVolver.setBackground(new java.awt.Color(44, 114, 243));
        btnVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVolverMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Volver");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btnVolverLayout = new javax.swing.GroupLayout(btnVolver);
        btnVolver.setLayout(btnVolverLayout);
        btnVolverLayout.setHorizontalGroup(
            btnVolverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
        );
        btnVolverLayout.setVerticalGroup(
            btnVolverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panContenedorLayout = new javax.swing.GroupLayout(panContenedor);
        panContenedor.setLayout(panContenedorLayout);
        panContenedorLayout.setHorizontalGroup(
            panContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panContenedorLayout.createSequentialGroup()
                .addGroup(panContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panContenedorLayout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(93, 93, 93)
                        .addComponent(btnPagar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panContenedorLayout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addGroup(panContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textCorreo1)
                            .addComponent(txtNoTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panContenedorLayout.createSequentialGroup()
                                .addGroup(panContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtFechaExpiracion)
                                    .addComponent(textCorreo2, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(panContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCVV, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textCorreo3))))))
                .addGap(0, 201, Short.MAX_VALUE))
        );
        panContenedorLayout.setVerticalGroup(
            panContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panContenedorLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(textCorreo1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtNoTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 158, Short.MAX_VALUE)
                .addGroup(panContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panContenedorLayout.createSequentialGroup()
                        .addComponent(textCorreo2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtFechaExpiracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panContenedorLayout.createSequentialGroup()
                        .addComponent(textCorreo3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtCVV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(138, 138, 138)
                .addGroup(panContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPagar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );

        jScrollPane1.setViewportView(panContenedor);

        javax.swing.GroupLayout jPanelInicioLayout = new javax.swing.GroupLayout(jPanelInicio);
        jPanelInicio.setLayout(jPanelInicioLayout);
        jPanelInicioLayout.setHorizontalGroup(
            jPanelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 672, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanelAzul, javax.swing.GroupLayout.PREFERRED_SIZE, 555, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanelInicioLayout.setVerticalGroup(
            jPanelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInicioLayout.createSequentialGroup()
                .addComponent(jPanelAzul, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane1))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanelInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNoTarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNoTarjetaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNoTarjetaActionPerformed

    private void txtFechaExpiracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaExpiracionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaExpiracionActionPerformed

    private void txtCVVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCVVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCVVActionPerformed

    private void btnPagarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPagarMouseClicked
        String fechaExpiracion = txtFechaExpiracion.getText().trim();

        String[] partesFecha = fechaExpiracion.split("/");
        String mes = partesFecha[0];
        String anio = partesFecha[1];

        TarjetaDTO tarjeta = new TarjetaDTO(txtNoTarjeta.getText(), Integer.parseInt(mes), Integer.parseInt(anio), txtCVV.getText());
        CobroDTO cobro = new CobroDTO(coordinador.getTotalPendiente(), "MXN", "Compra Boleto");
        PagoDTO pago = coordinador.realizarCompra(tarjeta, cobro);
        if (pago != null) {
            JOptionPane.showMessageDialog(null, "Pago realizado exitosamente", "Pago realizado", JOptionPane.INFORMATION_MESSAGE);
            reservacion.setPago(pago);
            try {
                coordinador.agregarReservacion(reservacion);
            } catch (CoordinadorException ex) {
                mostrarMensaje(ex.getMessage());
            }
            // -> aquí debe abrir el frame de resumen compra
            coordinador.mostrarDetalles(reservacion);
        } else {
            JOptionPane.showMessageDialog(null, "Pago no realizado", "No fue posible realizar el pago", JOptionPane.ERROR_MESSAGE);
            coordinador.volverAConsultarEvento();
        }
    }//GEN-LAST:event_btnPagarMouseClicked

    private void btnPagarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPagarMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPagarMouseEntered

    private void btnPagarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPagarMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPagarMouseExited

    private void txtNoTarjetaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNoTarjetaKeyReleased
        String texto = txtNoTarjeta.getText().replaceAll("[^0-9]", "");

        if (texto.length() > 16) {
            texto = texto.substring(0, 16);
        }

        StringBuilder formateado = new StringBuilder();
        for (int i = 0; i < texto.length(); i++) {
            if (i > 0 && i % 4 == 0) {
                formateado.append(" ");
            }
            formateado.append(texto.charAt(i));
        }

        txtNoTarjeta.setText(formateado.toString());
    }//GEN-LAST:event_txtNoTarjetaKeyReleased

    private void txtFechaExpiracionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFechaExpiracionKeyReleased

        String texto = txtFechaExpiracion.getText().replaceAll("[^0-9]", "");

        if (texto.length() > 4) {
            texto = texto.substring(0, 4);
        }

        if (texto.length() > 2) {
            texto = texto.substring(0, 2) + "/" + texto.substring(2);
        }

        txtFechaExpiracion.setText(texto);
    }//GEN-LAST:event_txtFechaExpiracionKeyReleased

    private void txtCVVKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCVVKeyReleased

        String texto = txtCVV.getText().replaceAll("[^0-9]", "");

        if (texto.length() > 3) {
            texto = texto.substring(0, 3);
        }

        txtCVV.setText(texto);
    }//GEN-LAST:event_txtCVVKeyReleased

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        coordinador.volverAConsultarEvento();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void btnVolverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverMouseClicked
        coordinador.volverAConsultarEvento();
    }//GEN-LAST:event_btnVolverMouseClicked

    private void txtNoTarjetaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNoTarjetaKeyTyped
        if (txtNoTarjeta.getText().length() >= 19) {
            evt.consume();
        }
    }//GEN-LAST:event_txtNoTarjetaKeyTyped

    private void txtFechaExpiracionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFechaExpiracionKeyTyped
        if (txtFechaExpiracion.getText().length() >= 5) {
            evt.consume();
        }
    }//GEN-LAST:event_txtFechaExpiracionKeyTyped

    private void txtCVVKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCVVKeyTyped
        if (txtCVV.getText().length() >= 3) {
            evt.consume();
        }
    }//GEN-LAST:event_txtCVVKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnPagar;
    private javax.swing.JPanel btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanelAzul;
    private javax.swing.JPanel jPanelAzulOscuro;
    private javax.swing.JPanel jPanelInicio;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panContenedor;
    private javax.swing.JLabel textCorreo1;
    private javax.swing.JLabel textCorreo2;
    private javax.swing.JLabel textCorreo3;
    private javax.swing.JLabel textPotroEventos;
    private javax.swing.JTextField txtCVV;
    private javax.swing.JTextField txtFechaExpiracion;
    private javax.swing.JTextField txtNoTarjeta;
    // End of variables declaration//GEN-END:variables
}
